usersegmentator:
  name: 'avito-user-segmentator'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: '8000'

mysql:
  host: 'mysql'
  max_cons: 50
  port: '3306'
  conn_timeout: 5

report:
  file_prefix: 'report_'
  file_ext: '.csv'
